# version: '3.4'
# services:
#   frontend:
#     build: ./frontend
#     platform: linux/x86_64 
#     container_name: app_frontend
#     ports:
#       - 3000:3000
#     depends_on:
#       backend:
#         condition: service_healthy
#     healthcheck:
#       test: ["CMD", "lsof", "-t", "-i:3000"] 
#       timeout: 10s
#       retries: 5
#   mongo:
#     image: mongo
#     container_name: app_mongo
#     ports:
#       - "27017:27017"
#     restart: always
#   backend: 
#     image: node
#     container_name: app_backend
#     restart: always
#     depends_on:
#       - mongo
#     environment:
#       - DB_HOST=mongo
#       - SERVER_PORT=3001
#     healthcheck:
#       test: ["CMD", "lsof", "-t", "-i:3001"]  
#     ports:
#       - 3001:3001
#     volumes:
#       - ./:/usr/app
#     working_dir: /usr/app
#     command: bash -c "npm install && npm start"




#     ----------------


version: '3.9'
services:
  frontend:
    build: ./frontend
    platform: linux/x86_64 
    container_name: app_frontend
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    build: ./backend
    platform: linux/x86_64
    restart: 'always'
    container_name: app_backend
    ports:
      - 3001:3001
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
      - SERVER_PORT=3001
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  mongo:
    image: mongo
    platform: linux/x86_64 
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
    